# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
# Tips for how to use docker compose.
# https://docs.docker.com/language/dotnet/containerize/#run-the-application
# Begin by declaring a network for your containers to talk to each other on.
# docker network create bookmarxnetwork
# To use the Docker Compose CLI, navigate to the directory containing your compose.yaml file.
# Then use the following to build and run your app:
# docker compose up --build
# To stop your app, use the following:
# docker compose down
# For local development copy this file to compose.local.yaml
version: '3.7'
services:
  bookmarks-api:
    build:
      context: .
      target: final
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - bookmarxnetwork
    volumes:
      - type: bind
        source: LOCAL_FIREBASE_CONFIG_PATH
        target: CONTAINER_FIREBASE_CONFIG_PATH
    env_file:
      - DEPLOYMENT_ENV_FILE

networks:
  bookmarxnetwork:
    external: true
