name: Bookmarx API - Deploy Container

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker build -t bookmarx-api:${{ github.sha }} -f Dockerfile .
        docker push bookmarx-api:${{ github.sha }}

    # Transform the values in the compose.yaml file for targeted release

    # Make a temp folder in the temp folder to store the files to make it easier to move them all at once

    # Upload the appropriate .env file to the server in a /tmp directory
    
    # Upload the firebase json file to the server in a /tmp directory
    
    # Upload the compose.yaml file to the server in a /tmp directory

    # Move the tmp uploaded files to the root container directory

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker compose pull
          docker compose -f ${{ secrets.API_CONTAINER_PATH }}/compose.yaml up -d --no-deps
